/**
 * AUTO-GENERATED FILE - DO NOT EDIT DIRECTLY
 * Source: all_tables_combined_clean.csv (Col_3)
 * Generated: 2025-09-29T13:34:33.676Z
 * Total entries: 1014
 */

export const COL3_VALUES = [
  "2-way valve, angle type (general)",
  "3 way valve 2",
  "AC Air compressor",
  "Actuator with manual actuated partial stroke test device.",
  "Actuator with remote actuated partial stroke test device.",
  "Actuator with side-mounted handwheel.",
  "Actuator with top-mounted handwheel.",
  "Actuator, without indication of type or control media",
  "Adsorber",
  "Agitator (general), stirrer (general)",
  "Agitator, anchor type",
  "Agitator, cross-beam type",
  "Agitator, disc type",
  "Agitator, flate-blade paddle type",
  "Agitator, gat paddle type",
  "Agitator, helical type",
  "Agitator, impeller type",
  "Agitator, propeller type",
  "Agitator, turbine type",
  "Agitator/mixer/fan",
  "Air blower",
  "Air cooled exchanger",
  "Air cooled heat exchanger 1",
  "Air cooled heat exchanger 2",
  "Air cooler (forced draft)",
  "Air cooler (induced draft)",
  "Air driven diaphragm pump",
  "Air fan cooler",
  "Air filter 1",
  "Air filter 2",
  "Air release valve",
  "Analyzer transmitter",
  "Angle blowdown valve",
  "Automatic flow regulator. XXX = FCV without indicator. XXX = FICV with integral indicator.",
  "Automatic reset on-off solenoid actuator. Non-latching on-off solenoid actuator.",
  "Automatic return, fail close",
  "Automatic return, fail open",
  "Automatic return, quick closing",
  "Automatic signal processor",
  "Automatic single-mode controller.",
  "Automatic three-mode controller.",
  "Automatic two-mode controller.",
  "Automation system panel mounted",
  "Average",
  "Averaging pitot tube.",
  "Back draft damper",
  "Back of control central panel mounted instrument",
  "Back of local panel mounted instrument",
  "Back pressure regulator",
  "Backpressure regulator, external pressure tap.",
  "Backpressure regulator, Internal pressure tap.",
  "Bag",
  "Bag filling machine",
  "Ball",
  "Ball float internally mounted in vessel. May be installed through top of vessel.",
  "Bandpass Filter",
  "Barrel, drum",
  "Basket strainer 1",
  "Basket strainer 2",
  "Battery",
  "Bell",
  "Bellows sealed valve.",
  "Bellows spring opposed actuator.",
  "Belt drier, roller-conveyor type drier",
  "Bin",
  "Biological Filter",
  "Bioreactor",
  "Bleeder valve",
  "Blind disc",
  "Blind flange",
  "Blower 1",
  "Blower 2",
  "Blower 3",
  "Blower or fan",
  "Blower, fan, ventilator, impeller type (general)",
  "Board mounted instrument",
  "Boiler",
  "Boiler with dome",
  "Boom loader",
  "Box truck",
  "Brackets vessel",
  "Breaching valve (BV-XXXX)",
  "Breakthrough",
  "Breather valve",
  "Bunker with conical bottom",
  "Butterfly valve",
  "Buzzer.",
  "Canned type vertical turbine pump",
  "Cap",
  "Capacitance or dielectric type level instrument",
  "Cartridge filter 1",
  "Cartridge fiter 2",
  "Cartridge gas filter",
  "Central control panel mounted instrument",
  "Centrifugal compressor 1",
  "Centrifugal compressor 2",
  "Centrifugal compressor 3",
  "Centrifugal compressor 4",
  "Centrifugal pump (submerged suction)",
  "Centrifugal, motor driven",
  "Centrifugal, turbine driven",
  "Centrifuge with perforated shell",
  "Centrifuge with solid shell",
  "Centrifuge, pusher type",
  "Centrifuge, screw-type with perforated shell",
  "Centrifuge, separator disc-type",
  "Centrifuge, skimmer type",
  "Centrifuges pumps (horizontal type)",
  "Centrifuges pumps (vertical type)",
  "Centrifuges pumps electric motor driven (horizontal type)",
  "Check valve (general)",
  "Check valve globe type",
  "Chimney tower hyperbolic",
  "Circle quadrant orifice plate",
  "Circuit breaker, 1-pole, manual reset.",
  "Circuit breaker, 3-pole, manual reset.",
  "Circuit interrupter, 1-pole, manual reset.",
  "Circuit interrupter, 3-pole, manual reset.",
  "Clamped flange coupling",
  "Closed spectable blind",
  "Closed tank with conical bottom",
  "Coil tubes heat exchanger",
  "Column (general)",
  "Column with bubble cap trays",
  "Column with fixed bed",
  "Column with fluidized bed",
  "Column with staggered baffle trays",
  "Column with two fixed bed sections and intermediate spray nozzle",
  "Column with valve trays",
  "Combustible gas detector",
  "Combustion chamber",
  "Communication link and system bus, between devices and functions of a fieldbus system.",
  "Communication link and system bus, between devices and functions of a shared display, shared control system.",
  "Communication link between a device and a remote calibration adjustment device or system.",
  "Communication link or bus connecting two or more independent microprocessor or computer-based systems.",
  "Compensator",
  "Compressor 1",
  "Compressor 2",
  "Compressor rotary type, vacuum pump, rotary piston type",
  "Compressor silencers",
  "Compressor, centrifugal type",
  "Compressor, ejector type, vacuum pump jet type",
  "Compressor, screw type",
  "Compressor, vacuum pump diaphragm type",
  "Compressor, vacuum pump liquid ring type",
  "Compressor, vacuum pump, fan, ventilator (general)",
  "Compressor, vacuum pump, reciprocating piston type",
  "Compressor, vacuum pump, roller vane type, compressor",
  "Compressor, vacuum pump, turbo type",
  "Computer",
  "Computer function on local area",
  "Concentric circle orifice plate, Restriction orifice",
  "Concentric reducer",
  "Condensate coalescer",
  "Condenser 1",
  "Condenser 2",
  "Conductivity, moisture, Single element sensing probe.",
  "Cone meter, Annular orifice meter.",
  "Cone type",
  "Cone type strainer",
  "Connection conventions a) and b): Left = Not connected. Right = Connected.",
  "Constant flow regulator.",
  "Container for solids, liquids, gases",
  "Container, Tank, Cistern",
  "Control integrator",
  "Control valve, 3-way distributing mode, general",
  "Control valve, 3-way mixing mode, general",
  "Control valve, angle type, general",
  "Control valve, general, continuously adjustability, shown with general actuator",
  "Controller, general",
  "Conveyor (general)",
  "Conveyor 1",
  "Conveyor 2",
  "Conveyor, belt type",
  "Conveyor, belt type in box",
  "Conveyor, belt type, reversible",
  "Conveyor, chain type, closed",
  "Conveyor, screw type, closed",
  "Conveyor, vibrating type, closed",
  "Cooling tower (general) 1",
  "Cooling tower (general) 2",
  "Cooling tower (general) 3",
  "Cooling tower, dry with forced draught",
  "Cooling tower, dry with induced draught",
  "Cooling tower, dry with natural draught",
  "Cooling tower, wet with forced draught",
  "Cooling tower, wet with induced draught",
  "Cooling tower, wet with natural draught",
  "Cooling tower, wet–dry with natural draught",
  "Coriollis flowmeter",
  "Counterflow forced draft",
  "Coupling",
  "CPI Separator",
  "Crane",
  "Crossflow inducted draft",
  "Crossing with connection",
  "Crusher (general)",
  "Crusher, cone type",
  "Crusher, hammer type",
  "Crusher, impact type",
  "Crusher, jaw type",
  "Crusher, roller type",
  "Crushing",
  "Crushing/grinding machine (general)",
  "Cylinder actuator, linear or rotating",
  "DCS Control accessible by operator",
  "DCS Control not accessible by operator",
  "Dead band",
  "Decanter, centrifuge, screw type with solid shell",
  "Deluge nozzles",
  "Demister pad 1",
  "Demister pad 2",
  "Device wiring point. Device wiring terminal.",
  "Dial pressure gauge",
  "Diaphgram valve",
  "Diaphragm actuator, double acting",
  "Diaphragm actuator, single acting",
  "Diaphragm pressure seal, flanged, threaded, socket welded, or welded.",
  "Diaphragm pressure seal, welded.",
  "Diaphragm pump",
  "Diaphragm seal connection (direct mount)",
  "Diesel driven",
  "Diesel motor",
  "Difference",
  "Differential pressure regulator, External pressure taps.",
  "Differential pressure regulator, internal pressure taps.",
  "Differential pressure switch actuator.",
  "Differential pressure type level instrument",
  "Differentiation",
  "Dip tube or other primary element and stilling well. May be installed through side of vessel. May be installed without stilling well",
  "Direct connected instrument",
  "Direct fired/heater furnace",
  "Direction in general, except for energy and signal flow 1",
  "Direction in general, except for energy and signal flow 2 Form 2",
  "Disc type",
  "Dished ends vessel",
  "Displacer internally mounted in vessel.",
  "Division",
  "Dome roof tank 1",
  "Dome roof tank 2",
  "Double acting, fail freeze",
  "Double pipe heat exchanger 1",
  "Double pipe heat exchanger 2",
  "Double pipe heat exchanger 3",
  "Double wall tank",
  "Drawing-to-drawing signal connector, signal flow from left to right (a and c) or right to left. (#) = Instrument tag number of the instrument on the referenced drawing sending or receiving the signal. (##) = Drawing or sheet number containing the referenced receiving or sending instrument.",
  "Drier 1",
  "Drier 2",
  "Drying oven, drying chamber, shelf drier 1",
  "Drying oven, drying chamber, shelf drier 2",
  "Dual function indicator",
  "Dummy cover",
  "Eccentric circle orifice plate",
  "Eccentric reducer bottom flat",
  "Eccentric reducer top flat",
  "Eccentric rotary disc valve",
  "Electric heater 1",
  "Electric heater 2",
  "Electric heater 3",
  "Electric heater 4",
  "Electric motor 1",
  "Electric motor 2",
  "Electric motor driven",
  "Electric motor driver",
  "Electric motor, AC",
  "Electric motor, DC",
  "Electric type",
  "Electrical diaphragm pump",
  "Electrical heating vessel",
  "Electrical motor actuator",
  "Electrohydraulic linear or rotary actuator.",
  "Electromagnetic actuator",
  "Electromagnetic separator",
  "Electromagnetic type",
  "Electronic or electrical continuously variable or binary signal, Functional diagram binary signal",
  "Electrostatic Precipitator Separator",
  "Electrostatic type",
  "Elevation of intervals height shown in mm above inside dead center bottom or vessel tan line",
  "Elevator, bucket type",
  "Elevator, bucket type Z-form",
  "Emergency shutdown system",
  "Emergency stop",
  "ESS Progam logic control from RTU",
  "ESS Program logic control not accessible by operator",
  "ET= Electric Traced. ST= Steam Traced",
  "Evaporator, re-boiler",
  "Excess flow valve",
  "Exchanger",
  "Expansion joint",
  "Extractor hood",
  "Extruder, piston type",
  "Extruder, screw type",
  "Eyewash and safety shower",
  "Fail at last position, Drift closed.",
  "Fail at last position, Drift open.",
  "Fail locked in last position",
  "Fail to close position",
  "Fail to open position",
  "Fan",
  "Feeder, rotary table type",
  "Fiberoptic sensing probe.",
  "Filled system direct connection",
  "Filled thermal element capillary tube.",
  "Filter 1",
  "Filter 2",
  "Filter 3",
  "Filter insert (general)",
  "Filter press, press filter",
  "Fin-fan cooler",
  "Final control element with positioner. Control valve with positioner.",
  "Final control element. Control valve",
  "Fire and gas system",
  "Fire-resistant and detonation-proof flame arrestor out to the atmosphere",
  "Firing system, burner (general)",
  "Fixed bed air Filter",
  "Fixed bed liquid Filter",
  "Fixed firewater monitor (FM-XXXX)",
  "Fixed roof tank 1",
  "Fixed roof tank 2",
  "Flame arrestor 1",
  "Flame arrestor 2",
  "Flame arrestor detonation-proof",
  "Flame arrestor explosion-proof",
  "Flame arrestor fire-resistant",
  "Flame rod flame detector.",
  "Flanged connection 1",
  "Flanged connection 2",
  "Flanged dummy cover",
  "Flanged instrument connection to process line, Flanged instrument connection to equipment.",
  "Flare stack",
  "Flare tip",
  "Flexible hose (flanged)",
  "Flexible hose (screwed)",
  "Float type level instrument mounted above tank",
  "Float type level instrument mounted below top of tank",
  "Float with guide wires. Location of readout should be noted, at grade, at top, or accessible from a ladder.",
  "Float-operated valve",
  "Floating roof tank",
  "Flotation cell",
  "Flow conditioner",
  "Flow element",
  "Flow element (orifice plat)",
  "Flow element (quick change fittings)",
  "Flow element (venturi tube or flow nozzle)",
  "Flow indicator",
  "Flow nozzle",
  "Flow recorder",
  "Flow straightening vanes, Flow conditioning element.",
  "Flow switch 1",
  "Flow switch 2",
  "Flow switch actuator.",
  "Flow transmitter",
  "Flow tube",
  "Flow, Coriollis type",
  "Flow, magnetic type",
  "Flow, nozzle type",
  "Flow, orifice type",
  "Flow, pitot tube type",
  "Flow, propeller or turbine type",
  "Flow, ultrasonic clamp-on type",
  "Flow, ultrasonic inline type",
  "Flow, Variable area type",
  "Flow, venturi type",
  "Flow, vortex type",
  "Flowmotion in direction of arrow",
  "Fluidized bed",
  "Fluidized bed drier",
  "Foot switch actuator.",
  "Forced-draft cooling tower",
  "Forklift, manually operated",
  "Forklift, truck",
  "Four-way five-ported on-off solenoid valve, Arrows indicates de-energized flow paths.",
  "Functional connection, instrument connection, control connection in process control diagrams (PCD) Line width 0,25",
  "Functional connection, pipeline Line width 0.5",
  "Functional diagram continuously variable signal, Electrical schematic ladder diagram signal and power rails.",
  "Funnel",
  "Furnace",
  "Fuse, non-resettable.",
  "Fusible link heat detector",
  "Fusible plug heat detector",
  "Gage glass externally mounted on vessel or standpipe.",
  "Gage integrally mounted on vessel Sight glass",
  "Gas bed filter fixed type",
  "Gas bottle",
  "Gas cylinder",
  "Gas engine driven",
  "Gas filter",
  "Gas filter (general)",
  "Gas filter, bag, candle or cartridge type",
  "Gas filter, belt or roll type",
  "Gas filter, high efficiency particulate air filter HEPA type",
  "Gas flare",
  "Gas turbine for compressor",
  "Gas/liquid filter coalescer",
  "Gauge class, external float or displacement level instrument",
  "Gear",
  "Gear pump",
  "Gear type, gearwheels type",
  "Generator (general)",
  "Generator, AC",
  "Generator, DC",
  "Generic actuator. Spring-diaphragm actuator.",
  "Generic damper, Generic louv",
  "Generic element without thermowell.",
  "Generic four-way valve, Four-way four-ported plug or ball valve, Arrows indicates failure or unactuated flow paths.",
  "Generic instrument connection to process line, Generic instrument connection to equipment.",
  "Generic moisture trap, Steam trap.",
  "Generic orifice plate, Restriction orifice",
  "Generic pressure - vacuum relief valve, Tank pressure - vacuum relief valve.",
  "Generic pressure safety valve, Pressure relief valve.",
  "Generic vacuum safety valve, Vacuum relief valve.",
  "Generic venturi tube, flow nozzle, or flow tube",
  "Gradient",
  "Gravity separator, settling chamber",
  "Gravity type, settling type",
  "Ground",
  "Guided electromagnetic signal, Guided sonic signal, Fiber optic cable",
  "Hair pin type heat exchanger 1",
  "Hair pin type heat exchanger 2",
  "Half open pipe",
  "Hammer type",
  "Hand actuated electric switch (HOA: Hand Off Auto)",
  "Hand operated",
  "Hand operated valve over-riding the motor action or manual",
  "Hand pump",
  "Hanger flange",
  "Heat [cool] traced generic instrument impulse line, Process line or equipment may or may not be traced",
  "Heat [cool] traced impulse or sample line from process",
  "Heat [cool] traced instrument, Instrument impulse line may or may not be traced",
  "Heat consumer",
  "Heat exchanger (general), condenser 1",
  "Heat exchanger (general), condenser 2",
  "Heat exchanger (M-shape)",
  "Heat exchanger floating head",
  "Heat exchanger of double-pipe type",
  "Heat exchanger of floating head type",
  "Heat exchanger of plate type",
  "Heat exchanger of spiral type 1",
  "Heat exchanger of spiral type 2",
  "Heat exchanger of spiral type 3",
  "Heat exchanger with coil shaped tubes",
  "Heat exchanger with finned tube",
  "Heat exchanger with finned tube and fan",
  "Heat exchanger with straight tubes (fixed-tube plates)",
  "Heat exchanger with U-shaped tubes 1",
  "Heat exchanger with U-shaped tubes 2",
  "Heat exchanger with U-shaped tubes 3",
  "Heat exchanger with U-shaped tubes 4",
  "Heater",
  "Heating coil",
  "Heating or cooling surface, general Form 1",
  "Heating or cooling surface, general Form 2",
  "Heating-cooling jacket vessel",
  "HEPA gas Filter",
  "High efficiency Filter",
  "High select",
  "High speed centrifuge",
  "Highpas filter",
  "Hook up number xxx",
  "Horizontal drum separator",
  "Horizontal separator with boot",
  "Horizontal vessel",
  "Horizontal vessel with boot",
  "Horn or siren.",
  "Hose",
  "Hose connection",
  "Hose reel",
  "Hot liquid boiler",
  "Hydraulic link",
  "Hydraulic signal",
  "Hydraulic type",
  "Hydraulic valve",
  "Hydrocracking",
  "Hydrocyclone 1",
  "Hydrocyclone 2",
  "Hydrodesulfurization",
  "IA may be replaced by PA [plant air], NS [nitrogen}, or GS.",
  "Impact separator",
  "Impact type",
  "In line static mixer",
  "In-line mixer",
  "In-line rotary mixer",
  "Inaccessible DCS",
  "Induced-draft cooling tower",
  "Industrial truck",
  "Injector",
  "Inlet baffle",
  "Inline filter",
  "Inline flow element coriolis type",
  "Inline flow element magnetic type",
  "Inline flow element thermal type",
  "Inline flow element ultrasonic type",
  "Inline flow element vortex type",
  "Insert probe. May be through top of vessel.",
  "Installed spade",
  "Instrument connections to process and equipment, Process impulse lines, Analyzer sample lines.",
  "Instrument electric power supply. Indicate voltage and type as required.",
  "Instrument hydraulic power supply.",
  "Instrument purge or flushing fluid. Instrument purge or flushing device or devices.",
  "Insulation joint or flange",
  "Integral orifice plate.",
  "Integrated block valve",
  "Interchangeable disc (blind disc)",
  "Interchangeable disc (open disc in function)",
  "Interlock",
  "Interlocking device",
  "Internal float or displacer type level instrument mounted on vessel",
  "Internal floating roof tank",
  "Internal functional, logic, or ladder diagram signal connector, Signal source to one or more signal receivers.",
  "Internal functional, logic, or ladder diagram signal connector. Signal receiver, one or more from a single source.",
  "Interruption of connection line",
  "Ionexchanger Filter",
  "Jacketed pipeline",
  "Jacketed vessel with dished ends and agitator driven by electric motor",
  "Jaw type",
  "Jet pump, liquid type ejector pump",
  "Jet type",
  "Kettle type chiller 3",
  "Kettle type exchanger 2",
  "Kettle type reboiler heat exchanger 1",
  "Key",
  "Kneader",
  "Knife valve",
  "Knock-out drum",
  "LCP displayed instrument",
  "Level alarm",
  "Level controller",
  "Level gauge",
  "Level indicator",
  "Level recorder",
  "Level regulator",
  "Level transmitter",
  "Level, electrode type",
  "Level, general",
  "Level, ultrasonic or radar type",
  "Level, vibration type",
  "Lift",
  "Light water station",
  "Limit switch, mechanical",
  "Limit switch, proximity",
  "Limit value, high or low",
  "Linear piston actuator with positioner.",
  "Linear piston actuator, Single acting spring opposed, Double acting.",
  "Liquid bed filter fixed type",
  "Liquid bed filter, biological type",
  "Liquid bed filter, ion exchanger type",
  "Liquid distributor",
  "Liquid Filter",
  "Liquid filter, bag, candle or cartridge type",
  "Liquid filter, belt or roll type",
  "Liquid Filters",
  "Liquid level switch actuator.",
  "Liquid ring compressor",
  "Liquid rotary filter, drum or disc type",
  "Liquid rotary filter, drum or disc type with scraper",
  "Liquid type, wet type",
  "Liquid/liquid filter coalescer",
  "Loading arm",
  "Lobe compressor",
  "Local manual reset",
  "Local manual reset facility",
  "Local panel mounted instrument",
  "Locally mounted instrument",
  "Low select",
  "Lowpass Filter",
  "Lube oil filter for compressor",
  "Magnetic flowmeter.",
  "Manhole",
  "Manual actuator, Hand actuator.",
  "Manual and remote reset on-off solenoid actuator, Latching on-off solenoid actuator.",
  "Manual or remote reset on-off solenoid actuator, Latching on-off solenoid actuator.",
  "Manual signal processor.",
  "Maximum selector",
  "Measuring, input, or readout device. [*] = Instrument tag number.",
  "Mechanical link or connection.",
  "Membrane",
  "Mill, horizontal rotation roller type",
  "Mill, impact type",
  "Mill, pulverizer (general)",
  "Mill, pulverizer hammer type",
  "Mill, vibration type",
  "Minimum flow valve",
  "Minimum selector",
  "Mixer",
  "Mixing noozle, injector",
  "Mixing path",
  "Mixing vessel",
  "Mode filter",
  "Mode filter indication",
  "Modulating solenoid actuator, Solenoid actuator for process on-off valve.",
  "Moisture trap with equalizing line.",
  "Monitoring control system",
  "motor 1",
  "Motor 2",
  "Motor driven turbin",
  "Motor operated actuator. Electric, pneumatic, or hydraulic Linear or rotary action.",
  "Motor operated valve",
  "Multi-hole orifice plate",
  "Multiplication",
  "Needel valve",
  "Needle valve",
  "Non return valve, general Form 1",
  "Non return valve, general Form 2",
  "Normally close relay contact.",
  "Normally closed ball diaghragm",
  "Normally closed single circuit momentary pushbutton switch, Form B switch contact, Stack symbols to form multi-pole switches, Combine with symbols 5 or 6 to form toggle or rotary actuated switches.",
  "Normally closed/normally open double circuit momentary pushbutton switch, Double Pole Single Throw (DPST) switch contact, Stack symbols to form multi-pole switches, Combine with symbols 5 or 6 to form toggle or rotary actuated switches",
  "Normally open relay contact.",
  "Normally open single circuit momentary pushbutton switch, Form A switch contact, Stack symbols to form multi-pole switches, Combine with symbols 5 or 6 to form toggle or rotary actuated switches.",
  "Normally open, normally closed relay contact.",
  "Off time delay.",
  "Oil burner",
  "On time delay.",
  "On-Off Control station",
  "Onion tank",
  "Open bulk storage",
  "Open channel flume",
  "Open channel weir plate.",
  "Open disc",
  "Open drain/tundish",
  "Open spectacle blind",
  "Opposed blade damper, Opposed blade louver",
  "Order delay",
  "Orifice plate",
  "Orifice plate in quick-change fitting",
  "Output signal generated when one or more inputs exist",
  "Oxygen-enriched Filter",
  "Packed column 1",
  "Packed column 2",
  "Packing 1",
  "Packing 2",
  "Packing/internal bad",
  "Paddle wheel or level type level instrument",
  "Palletizer",
  "Parallel blade damper, Parallel blade louver",
  "PCI, circle form, central control system",
  "PCI, circle form, field mounted",
  "PCI, circle form, local control system",
  "PCI, extended form, central control system",
  "PCI, extended form, field mounted",
  "PCI, extended form, local control system",
  "PD Meter",
  "Pelletizing disc",
  "Permanent magnet",
  "Permanent magnet separator",
  "Permanent magnet variable speed coupling",
  "pH, ORP, Dual element sensing probe.",
  "Pig launcher/receiver",
  "Pilot actuated relief or safety valve actuator, Pilot pressure sensing line deleted if sensing is internal.",
  "Pilot gate valve",
  "Pilot light",
  "Pilot light.",
  "Pilot line, signal lines in process flow diagrams (PFD)",
  "Pinch valve",
  "Pipeline",
  "Pipeline with thermal insulation",
  "Piping, heated or cooled and insulated",
  "Piston compressor",
  "Piston type positive displacement pump",
  "Piston-operated valve",
  "Pit vessel",
  "Pitot tube and averaging pitot tube",
  "Plate and frame heat exchanger 1",
  "Plate exchanger 3",
  "Plate heat exchanger 2",
  "PLC Control accessible by operator",
  "PLC Control not accessible by operator",
  "Plug or cock valve",
  "Plug valve",
  "Plugged valve for pressure test gauge",
  "Pneumatic diaphragm pump",
  "Pneumatic metering pump",
  "Pneumatic signal, continuously variable or binary.",
  "Pneumatic type",
  "Point of measurement",
  "Polygon table",
  "Portable firewater monitor (PM-XXXX)",
  "Positive displacement flowmeter.",
  "Positive displacement meter",
  "Powered valve",
  "Precipitator wet, electrostatic type",
  "Press Filter",
  "Press, piston type",
  "Press, roller type",
  "Pressure controller",
  "Pressure gage",
  "Pressure indicating",
  "Pressure indicator",
  "Pressure recorder",
  "Pressure recording",
  "Pressure safety element, Pressure rupture disk, Pressure relief.",
  "Pressure safety element, Vacuum rupture disk, Vacuum relief.",
  "Pressure switch actuator.",
  "Pressure transmitter",
  "Pressure-balanced diaphragm actuator.",
  "Pressure-reducing regulator w/ integral outlet pressure relief and pressure gauge.",
  "Pressure-reducing regulator, external pressure tap.",
  "Pressure-reducing regulator, Internal pressure tap.",
  "Primary Filter Mid-effect Filter",
  "Printed circuit head exchanger",
  "Progressing cavity pump",
  "Proportional feeder (general)",
  "Proportional feeder, metering type",
  "Proportional feeder, rotary valve type",
  "Proportioning pump",
  "Protective palette covering",
  "Pump A off Pump B",
  "Pump, centrifugal type",
  "Pump, diaphragm type",
  "Pump, gear type",
  "Pump, liquid type (general)",
  "Pump, progressive cavity type",
  "Pump, reciprocating piston type",
  "Pump, screw type",
  "Quarter turn valve",
  "Quarter turn valve (double acting)",
  "Quick opening closure",
  "Radar",
  "Radiation or sonic sensing",
  "Radiation, multi-point or continuous.",
  "Radiation, single point, Sonic",
  "Reactor",
  "Rear of local panel",
  "Reciprocating air compressor 1",
  "Reciprocating air compressor 2",
  "Reciprocating air compressor 3",
  "Reciprocating air compressor 4",
  "Reciprocating pump 1",
  "Reciprocating pump 2",
  "Reciprocating pump 3",
  "Reciprocating, direct acting",
  "Reciprocating, engine driven",
  "Reciprocating, motor driven",
  "Reducer",
  "Removable spool piece",
  "Restriction orifice",
  "Roll air Filter",
  "Roller conveyor",
  "Roller type",
  "Rotameter",
  "Rotameter/variable orifice meter",
  "Rotary (gear pump) type",
  "Rotary drum drier, rotary drier, tumbling drier",
  "Rotary filter",
  "Rotary liquid Filter",
  "Rotary piston actuator, May be single acting spring opposed or double acting",
  "Rotary selector switch.",
  "Rotary valve",
  "Rupture disc",
  "Rupture disk or safety head for pressure relief",
  "Rupture disk or safety head for vacuum relief",
  "Safety shower & eye washer",
  "Safety shower and eye wash station (SS-XXXX)",
  "Safety valve, spring loaded, angle type, general",
  "Safety valve, spring loaded, globe angle type",
  "Safety valve, spring loaded, globe type",
  "Safety valve, spring loaded, straight type, general",
  "Sample conditioner or other analysis accessory, flanged.",
  "Sample connection",
  "Sample insert probe, flanged.",
  "Sampler",
  "Schoepentoeter",
  "Scrapper launcher/receiver and closure",
  "Screening device with coarse and fine screens",
  "Screening device, basket reel type",
  "Screening device, coarse rake type",
  "Screening device, fine rake type",
  "Screening device, rotating drum type",
  "Screening device, sieve, strainer, general",
  "Screening device, sieve, strainer, vibrating type",
  "Screw compressor 1",
  "Screw compressor 2",
  "Screw compressor 3",
  "Screw pump",
  "Seal gas filter for compressor",
  "Secondary pipeline",
  "Selector",
  "Self draining valve",
  "Self-operating back-pressure control valve",
  "Self-operating pressure-reducing control valve",
  "Self-operating release valve (steam trap)",
  "Sensor vibration, general",
  "Sensor, built-in type, general",
  "Sensor, general",
  "Sensor, rotation",
  "Sensor, vibration, rotating machines",
  "Separator, cyclone type",
  "Separator, precipitator electrostatic type",
  "Separator, scrubber venturi type",
  "Separator, scrubber wet type",
  "Separator, sifter (general)",
  "Serial link signal or internal system link",
  "Set point Form 1",
  "Set point Form 2",
  "Settlers",
  "Shaping machine, horizontal type (general)",
  "Shaping machine, vertical type (general)",
  "Shell and tube heat exchanger 1",
  "Shell and tube heat exchanger 2",
  "Ship",
  "Shutdown system at unit control panel",
  "Shutdown valve – closing on failure",
  "Shutdown valve – opening on failure",
  "Sieve tray, screen or sieve element",
  "Sight glass 1",
  "Sight glass 2",
  "Signal converter, transmitter",
  "Signal flow",
  "Signal from panel",
  "Signal input to logic diagram.",
  "Signal output from logic diagram.",
  "Signal relays",
  "Signal to panel",
  "Silencer 1",
  "Silencer 2",
  "Single flange",
  "Single pass heat exchanger 1",
  "Single pass heat exchanger 2",
  "Single Pole Double Throw (SPDT) normally closed /normally open toggle switch.",
  "Single Pole Single Throw (SPST) normally closed toggle switch, Form B switch contact, Select a) or b) depending on actuating device, Combine with symbols 11 thru 16, 20 and 21.",
  "Single Pole Single Throw (SPST) normally open toggle switch, Form A switch contact. Select a) or b) depending on actuating device. Combine with symbols 11 thru 16, 20, and 21.",
  "Siphon",
  "SIS Displayed instrument",
  "Slide valve",
  "Slope",
  "Smoke detector",
  "Socket welded instrument connection to process line, Socket welded instrument connection to equipment.",
  "Socket, connection noozle",
  "Solenoid coil.",
  "Solenoid valve",
  "Solidifier",
  "Solidifier closed type",
  "Solidifier for waste water treatment plant open type",
  "Sonic flowmeter, Ultrasonic flowmeter.",
  "Spacer ring for future spade",
  "Sparger/spray",
  "Special piping item",
  "Specialty item",
  "Spherical vessel",
  "Spherical vessel on legs",
  "Spray cooler",
  "Spray drier",
  "Spray Noozle",
  "Spray scrubber",
  "Spring gate valve",
  "Spring or weight actuated relief or safety valve actuator",
  "Spring-diaphragm actuator with positioner.",
  "Stack, chimney",
  "Standard pitot tube.",
  "Start stop",
  "Status lamp mounted on central control panel 1",
  "Status lamp mounted on central control panel 2",
  "Status lamp mounted on local panel",
  "Status lamp mounted on main control room panel",
  "Steam generator with hot liquid as generating media",
  "Strain gage or other electronic type sensor.",
  "Strainer",
  "Strainer 1",
  "Strainer 2",
  "Submersible pump",
  "Subtraction",
  "Suction filter 1",
  "Suction filter 2",
  "Summation",
  "Sump pump",
  "Support brakker",
  "Support leg",
  "Support ring",
  "Support skirt",
  "Surface mounted instrument",
  "Swing check valve (Form 1)",
  "Swing check valve (Form 2)",
  "Swirl deck",
  "T-branch, form 1",
  "T-branch, form 2",
  "T-type strainer",
  "Tank car, tank wagon",
  "Tank with conical roof and flat bottom",
  "Tank with dished roof",
  "Tank, Vessel",
  "Tank, Vessel with dished end",
  "Target flowmeter.",
  "Tema type AEL",
  "Tema type AEM",
  "Tema type BEU",
  "Tema type BKU",
  "Tema type NEN",
  "Temperature element",
  "Temperature indicator",
  "Temperature measurement, general in pipeline and ducts",
  "Temperature recorder",
  "Temperature regulator (filled steam type)",
  "Temperature regulator, Filled thermal system.",
  "Temperature switch actuator.",
  "Temperature transmitter",
  "Temporary strainer",
  "The filter",
  "Thermal heat detector combined",
  "Thermal insulation vessel",
  "Thermal mass flowmeter.",
  "Thermal overload",
  "Thermal safety element, Fusible plug or disk.",
  "Thermometer",
  "Thermowell",
  "Thin-film evaporator",
  "Threaded instrument connection to process line, Threaded instrument connection to equipment.",
  "Three-position toggle or rotary maintained position pushbutton switch actuator, Combine with symbols 2, 3, and 4 to form single or multi-pole switches.",
  "Tie in number xxx",
  "Tracer for heating or cooling",
  "Transducer",
  "Transformer",
  "Transport",
  "Trap",
  "Tray (general)",
  "Tray column (general)",
  "Tray column 1",
  "Tray column 2",
  "Tray with baffle",
  "Tray, bubble-cap type",
  "Tray, valve type",
  "Truck/road tanker",
  "Tube bundle, heat exchanger of floating head type",
  "Tube bundle, heat exchanger with U-shaped tubes",
  "Tubular",
  "Turbin driven",
  "Turbine (general)",
  "Turbine driver GT= Gas Turbine ST= Steam Turbine",
  "Turbine flowmeter, Propeller flowmeter.",
  "Turbine meter",
  "Turbine/expander 1",
  "Turbine/expander 2",
  "Turbo compressor",
  "Turbo drier, disc drier, moving shelf drier",
  "Two out of n voting",
  "Two-position toggle or rotary maintained position pushbutton switch actuator, Combine with symbols 2, 3, and 4 to form single or multi-pole switches.",
  "Typical control panel",
  "Ultraviolet flame detector",
  "Undefined signal, Use for Process Flow Diagrams.",
  "Unguided electromagnetic signals, light, radiation, radio, sound, wireless.",
  "Unit control panel 1",
  "Unit control panel 2",
  "Utility station",
  "V-cone flowmeter",
  "Valve locking device",
  "Valve orifice",
  "Valve, 2-way on-off valve, straight type (general)",
  "Valve, angle ball type",
  "Valve, angle globe type",
  "Valve, ball type",
  "Valve, butterfly type (Form 1)",
  "Valve, butterfly type (Form 2)",
  "Valve, control type, continuous operated",
  "Valve, gate type",
  "Valve, globe type",
  "Valve, needle type",
  "Valve, three way ball type",
  "Valve, three way globe type",
  "Valve, three way type (general)",
  "Vane pack",
  "Vane type mist extractor",
  "Vaporizer, kettle type",
  "Variabel speed driven",
  "Variable area flowmeter with integral manual adjusting valve, Instrument tag bubble required with (b)",
  "Variable area flowmeter.",
  "Variable speed",
  "Various mixer 1",
  "Various mixer 2",
  "Various mixer 3",
  "VDU displayed instrument in dcs",
  "Vent",
  "Vent (outlet to the atmosphere for steam/gas)",
  "Vent stack",
  "Venturi tube.",
  "Vertical – packed",
  "Vertical barrel pump centrifugal",
  "Vertical coalescer",
  "Vertical filter separator (cartridge type)",
  "Vertical fire pump",
  "Vertical separator/scrubber",
  "Vertical submersible pump",
  "Vertical turbine pump",
  "Vertical vessel",
  "Vertical vessel – Trayed type",
  "Vessel mounted electric heater",
  "Vessel with conical roof and bottom",
  "Vessel with dished bottom and surface indication",
  "Vessel with dished ends and electrical heating",
  "Vessel with dished ends and heating/ cooling jacket",
  "Vessel with dished ends and support brackets",
  "Vessel with dished ends and support legs",
  "Vessel with dished ends and support ring",
  "Vessel with dished ends and support skirt",
  "Vessel with dished ends and thermal insulation",
  "Vessel with dished roof and conical bottom",
  "Vessel with dome",
  "Vessel with full-tube heating/cooling coil",
  "Vessel with pit",
  "Vessel with semi-tube heating/cooling coil",
  "Vessel with two different diameters",
  "Vibration type",
  "Viewing glass",
  "Viewing glass with lighting",
  "Vortex breaker 1",
  "Vortex breaker 2",
  "Vortex shedding flowmeter",
  "Wedge meter",
  "Weighing, general",
  "Weight gate valve",
  "Welded instrument connection to process line, Welded instrument connection to equipment.",
  "Wellhead",
  "Wellstream coolers",
  "Wet gas meter",
  "Witches hat strainer complete with drop out spool",
  "Y-type strainer"
] as const;

export type Col3Value = typeof COL3_VALUES[number];

export class Col3Catalog {
  /** All values in sorted order */
  static readonly all: Col3Value[] = [...COL3_VALUES];

  /** O(1) membership test */
  private static readonly set = new Set(COL3_VALUES as readonly string[]);

  /** Check if a value exists (case-sensitive) */
  static has(value: string): value is Col3Value {
    return Col3Catalog.set.has(value);
  }

  /** Find values containing a case-insensitive substring */
  static search(sub: string): Col3Value[] {
    const needle = sub.toLowerCase();
    return Col3Catalog.all.filter(v => v.toLowerCase().includes(needle));
  }

  /** Return a normalized version (trimmed) if valid */
  static normalize(value: string): Col3Value | undefined {
    const trimmed = value.trim();
    return Col3Catalog.has(trimmed) ? (trimmed as Col3Value) : undefined;
  }
}

// Convenience: export union type explicitly (for IDE intellisense)
export type { Col3Value as Col3 };
